name: Assets CI

on:
  push:
    branches:
    - main
    paths:
    - 'src/assets/**'
  pull_request:
    branches:
    - main
    paths:
    - 'src/assets/**'
    - 'images/**'
  workflow_dispatch:

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build image
      uses: mamezou-tech/buildpacks-action@master
      with:
        image: 'checkout-app'
        tag: '${{github.sha}}'
        path: 'src/assets'
        builder: 'gcr.io/paketo-buildpacks/builder:base'
        env: 'TEST=TEST'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1         

    - name: Deploy to AWS
      run: |
        # Your AWS CLI commands go here
        aws s3 ls 

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: assets
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker images
        docker tag assets-app:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG           
