name: Checkout CI

on:
  push:
    branches:
    - main
    paths:
    - 'src/checkout/**'
  pull_request:
    branches:
    - main
    paths:
    - 'src/checkout/**'
    - 'images/**'
  workflow_dispatch:

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Run CI script
      run: |
        bash src/checkout/scripts/ci.sh

    - name: Build image
      uses: mamezou-tech/buildpacks-action@master
      with:
        image: 'test-app'
        tag: '${{github.sha}}'
        path: 'src/'
        builder: 'gcr.io/paketo-buildpacks/builder:base'
        env: 'TEST=TEST'
