name: Catalog CI

on:
  push:
    branches:
    - main
    paths:
    - 'src/catalog/**'
  pull_request:
    branches:
    - main
    paths:
    - 'src/catalog/**'
    - 'images/**'
  workflow_dispatch:

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: '^1.18.1'

    - name: Run CI script
      run: |
        src/catalog/scripts/ci.sh

    - name: Build image
      uses: mamezou-tech/buildpacks-action@master
      with:
        image: 'catalog-app'
        tag: '${{github.sha}}'
        path: 'src/catalog'
        builder: 'gcr.io/paketo-buildpacks/builder:base'
        env: 'TEST=TEST'