name: Orders CI

on:
  push:
    branches:
    - main
    paths:
    - 'src/orders/**'
  pull_request:
    branches:
    - main
    paths:
    - 'src/orders/**'
    - 'images/**'
  workflow_dispatch:

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 17

    - name: Run CI script
      env:
        MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
      run: |
        src/orders/scripts/ci.sh

    - name: Build image
      uses: mamezou-tech/buildpacks-action@master
      with:
        image: 'orders-app'
        tag: '${{github.sha}}'
        path: 'src/orders'
        builder: 'gcr.io/paketo-buildpacks/builder:base'
        env: 'TEST=TEST'
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1         

    - name: Deploy to AWS
      run: |
        # Your AWS CLI commands go here
        aws s3 ls 

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public      

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: "public.ecr.aws/i5t0v8v6"
        REPOSITORY: orders
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker images
        docker tag orders-app:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG     